function sizeInPixel = VisualAngleToPixel(...
    angle, ...
    viewingDistance, ...
    monitorWidth, ...
    monitorResolution ...
    )
% Convert a visual angle in degrees into distance in pixel
% 
% Note that this conversion assumes that the visual angle is measured from
% the point on the monitor which is closest to participant's eye
% 
% function sizeInPixel = VisualAngleToPixel(...
%     angle, ...
%     viewingDistance, ...
%     monitorWidth, ...
%     monitorResolution ...
%     )
% 

degreePerPixel = atan2d(0.5 * monitorWidth, viewingDistance) / ...
    (0.5 * monitorResolution(1));

sizeInPixel = angle / degreePerPixel;
